import type { Metadata, Viewport } from "next";
import "./globals.css";
import { monument, neueMontreal, overusedGrotesk, jetbrainsMono, dirtyline } from "./fonts";
import { themeScript } from "./theme";
import Shell from "./Shell";

const SITE = process.env.NEXT_PUBLIC_SITE_URL || "https://www.auvancestudio.ca";
const DESCRIPTION =
  "Auvance is a Vancouver web studio building custom, high-converting websites for local businesses. Fixed price. You own everything. No lock-in.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: {
    default: "Auvance — Vancouver Web Studio",
    template: "%s — Auvance",
  },
  description: DESCRIPTION,
  applicationName: "Auvance",
  keywords: [
    "Vancouver web studio",
    "web design Vancouver",
    "custom websites",
    "local business websites",
    "conversion-focused web design",
    "Auvance",
  ],
  authors: [{ name: "Auvance" }],
  creator: "Auvance",
  publisher: "Auvance",
  alternates: { canonical: "/" },
  // og:image / twitter:image are generated by opengraph-image.tsx & twitter-image.tsx
  openGraph: {
    type: "website",
    locale: "en_CA",
    url: SITE,
    siteName: "Auvance",
    title: "Auvance — Vancouver Web Studio",
    description: DESCRIPTION,
  },
  twitter: {
    card: "summary_large_image",
    title: "Auvance — Vancouver Web Studio",
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  // Theme-aware favicon: black crown in light mode, white crown in dark mode.
  icons: {
    icon: [
      { url: "/crown-black.svg", media: "(prefers-color-scheme: light)", type: "image/svg+xml" },
      { url: "/crown-white.svg", media: "(prefers-color-scheme: dark)", type: "image/svg+xml" },
    ],
    shortcut: "/crown-black.svg",
    apple: "/crown-white.svg",
  },
  category: "technology",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#e7e8ea" },
    { media: "(prefers-color-scheme: dark)", color: "#0c0d0f" },
  ],
  width: "device-width",
  initialScale: 1,
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": ["Organization", "ProfessionalService"],
      "@id": `${SITE}/#org`,
      name: "Auvance",
      url: SITE,
      email: "therealauvance@gmail.com",
      telephone: "+1-236-978-0637",
      description: DESCRIPTION,
      areaServed: "Vancouver, BC",
      address: {
        "@type": "PostalAddress",
        addressLocality: "Vancouver",
        addressRegion: "BC",
        addressCountry: "CA",
      },
      logo: `${SITE}/crown-black.svg`,
    },
    {
      "@type": "WebSite",
      "@id": `${SITE}/#website`,
      url: SITE,
      name: "Auvance — Vancouver Web Studio",
      description: DESCRIPTION,
      publisher: { "@id": `${SITE}/#org` },
      inLanguage: "en-CA",
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const fontVars = `${monument.variable} ${neueMontreal.variable} ${overusedGrotesk.variable} ${jetbrainsMono.variable} ${dirtyline.variable}`;

  return (
    <html lang="en" data-theme="dark" className={fontVars} suppressHydrationWarning>
      <body>
        {/* Render-blocking: set the saved theme before first paint (no flash). */}
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        {/* Organization + WebSite structured data (JSON-LD). */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <Shell>{children}</Shell>
      </body>
    </html>
  );
}
